### ISSUE TITLE
ACPI BIOS and AMD gpu error during boot after 21.10 upgrade

### ISSUE THREAD

**Issue by mbrugnoni** [pop-os/linux#115]
Started getting this during boot after upgrading to 21.10

![image](https://user-images.githubusercontent.com/6556673/149562319-bedec401-9491-40fc-a45c-b1f6cd5ad602.png)

**Comment by dth0** [comment]
the AMD issue was already fixed in the [5.15.16](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c?id=63ad5371cd1e379519395c49a4b6a652c36c98e5) release. Now regarding the ACPI errors, did you try the last update and is your bios up to date as well?

**Comment by mbrugnoni** [comment]
Makes sense as Pop is still on 5.15.15 kernel. 

I am fully up to date on Pop 21.10 and still seeing those errors. Checked for any BIOS updates (it's an old motherboard) and looks like there may be one I can do. May give that a shot to see if there's any difference. 

System is fully usable and still boots fine after displaying these messages.
